name: "KW: CloudFlare - Delete Tunnel"
description: "Removes CloudFlare ZaroTrust Tunnel"
author: "KouraWealth"

inputs:
  id:
    description: "Tunnel ID"
  name:
    description: "Tunnel name"
  account_id:
    description: "CloudFlare Account ID"
    required: true
  token:
    description: "CloudFlare API token"
    required: true

runs:
  using: "node20"
  main: "main.js"

branding:
  icon: "globe"
  color: "green"
